# Generated by Django 5.1.7 on 2025-03-26 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=222)),
                ('brend', models.CharField(max_length=222)),
                ('narx1', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('narx2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('miqdor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('olchov', models.CharField(max_length=10)),
                ('oxirgi_sana', models.DateTimeField(blank=True, null=True)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('dokon', models.CharField(max_length=200)),
                ('manzil', models.CharField(max_length=200)),
                ('qarz', models.FloatField()),
                ('tel', models.CharField(max_length=20)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('jami_summa', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('qarz', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tolandi', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bolim')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahsulot')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='sotuvchi/')),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bolim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
